/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph;

import ox.xtext.peweb.graph.AbstractGraphRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GraphRuntimeModule extends AbstractGraphRuntimeModule {
}
