/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph;

import ox.xtext.peweb.graph.GraphStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GraphStandaloneSetup extends GraphStandaloneSetupGenerated {
  public static void doSetup() {
    new GraphStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
