/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.ide;

import ox.xtext.peweb.arithmetic.ide.AbstractArithmeticIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ArithmeticIdeModule extends AbstractArithmeticIdeModule {
}
