/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ox.xtext.peweb.arithmetic.ArithmeticRuntimeModule;
import ox.xtext.peweb.arithmetic.ArithmeticStandaloneSetup;
import ox.xtext.peweb.arithmetic.ide.ArithmeticIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ArithmeticIdeSetup extends ArithmeticStandaloneSetup {
  @Override
  public Injector createInjector() {
    ArithmeticRuntimeModule _arithmeticRuntimeModule = new ArithmeticRuntimeModule();
    ArithmeticIdeModule _arithmeticIdeModule = new ArithmeticIdeModule();
    return Guice.createInjector(Modules2.mixin(_arithmeticRuntimeModule, _arithmeticIdeModule));
  }
}
