/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ox.xtext.peweb.arithmetic.ui.AbstractArithmeticUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ArithmeticUiModule extends AbstractArithmeticUiModule {
  public ArithmeticUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
