/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ox.xtext.peweb.question.ui.internal.QuestionActivator;

public class QUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return QuestionActivator.getInstance().getInjector("ox.xtext.peweb.question.Q");
	}

}
