/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ox.xtext.peweb.graph.ui.internal.GraphActivator;

public class GraphUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GraphActivator.getInstance().getInjector("ox.xtext.peweb.graph.Graph");
	}

}
