/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.peweb;

import com.google.inject.Injector;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.eclipse.xtext.peweb.customview.ViewRetriever;
import org.eclipse.xtext.peweb.editorgen.ViewSpecification;
import org.eclipse.xtext.peweb.servlet.PeServlet;
import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.web.server.IServiceContext;
import org.eclipse.xtext.web.servlet.HttpServiceContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import ox.xtext.peweb.question.peweb.QPeWebSetup;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "PeServices", urlPatterns = "/pe-service/*")
@SuppressWarnings("all")
public class QPeServlet extends PeServlet {
  private DisposableRegistry disposableRegistry;
  
  private Injector injector;
  
  private ViewRetriever viewRetriever;
  
  @Override
  public Injector getInjector() {
    Injector _xifexpression = null;
    if ((this.injector == null)) {
      _xifexpression = this.injector = new QPeWebSetup().createInjectorAndDoEMFRegistration();
    } else {
      return this.injector;
    }
    return _xifexpression;
  }
  
  @Override
  public ViewRetriever getViewRetriever() {
    if ((this.viewRetriever == null)) {
      ViewRetriever _viewRetriever = new ViewRetriever();
      this.viewRetriever = _viewRetriever;
      this.viewRetriever.nodeMap = ViewSpecification.getNodeMap();
      this.viewRetriever.componentMap = ViewSpecification.getComponentMap();
    }
    return this.viewRetriever;
  }
  
  @Override
  public void init() {
    try {
      super.init();
      this.disposableRegistry = this.getInjector().<DisposableRegistry>getInstance(DisposableRegistry.class);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Override
  public void doGet(final HttpServletRequest request, final HttpServletResponse response) {
    try {
      final String t = new HttpServiceContext(request).getParameter(IServiceContext.SERVICE_TYPE);
      System.out.println(("Start : " + t));
      super.doGet(request, response);
      System.out.println(("Done :" + t));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Override
  public void destroy() {
    if ((this.disposableRegistry != null)) {
      this.disposableRegistry.dispose();
      this.disposableRegistry = null;
    }
    super.destroy();
  }
}
