/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.scoping;

import ox.xtext.peweb.arithmetic.scoping.AbstractArithmeticScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ArithmeticScopeProvider extends AbstractArithmeticScopeProvider {
}
