/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.peweb;

import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import ox.xtext.peweb.arithmetic.peweb.AbstractArithmeticPeWebModule;
import ox.xtext.peweb.arithmetic.peweb.ArithmeticPeFileResourceHandler;
import ox.xtext.peweb.arithmetic.peweb.ArithmeticPeResourceBaseProvider;

/**
 * Use this class to register additional components to be used within the pe web application.
 */
@SuppressWarnings("all")
public class ArithmeticPeWebModule extends AbstractArithmeticPeWebModule {
  public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
    return ArithmeticPeFileResourceHandler.class;
  }
  
  public Class<? extends IResourceBaseProvider> bindIResourceBaseProvider() {
    return ArithmeticPeResourceBaseProvider.class;
  }
}
