/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.peweb;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ox.xtext.peweb.arithmetic.ArithmeticRuntimeModule;
import ox.xtext.peweb.arithmetic.ArithmeticStandaloneSetup;
import ox.xtext.peweb.arithmetic.ide.ArithmeticIdeModule;
import ox.xtext.peweb.arithmetic.peweb.ArithmeticPeWebModule;

/**
 * Initialization support for running Xtext languages in pe web applications.
 */
@SuppressWarnings("all")
public class ArithmeticPeWebSetup extends ArithmeticStandaloneSetup {
  @Override
  public Injector createInjector() {
    ArithmeticRuntimeModule _arithmeticRuntimeModule = new ArithmeticRuntimeModule();
    ArithmeticIdeModule _arithmeticIdeModule = new ArithmeticIdeModule();
    ArithmeticPeWebModule _arithmeticPeWebModule = new ArithmeticPeWebModule();
    return Guice.createInjector(Modules2.mixin(_arithmeticRuntimeModule, _arithmeticIdeModule, _arithmeticPeWebModule));
  }
}
