/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Of Questionnaire</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ox.xtext.peweb.question.q.QPackage#getEndOfQuestionnaire()
 * @model
 * @generated
 */
public interface EndOfQuestionnaire extends NextSection
{
} // EndOfQuestionnaire
