/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiple Choice Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.question.q.MultipleChoiceQuestion#getAnswers <em>Answers</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.question.q.QPackage#getMultipleChoiceQuestion()
 * @model
 * @generated
 */
public interface MultipleChoiceQuestion extends Question
{
  /**
   * Returns the value of the '<em><b>Answers</b></em>' containment reference list.
   * The list contents are of type {@link ox.xtext.peweb.question.q.MultipleChoiceAnswer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Answers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Answers</em>' containment reference list.
   * @see ox.xtext.peweb.question.q.QPackage#getMultipleChoiceQuestion_Answers()
   * @model containment="true"
   * @generated
   */
  EList<MultipleChoiceAnswer> getAnswers();

} // MultipleChoiceQuestion
