/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Next Section</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ox.xtext.peweb.question.q.QPackage#getNextSection()
 * @model
 * @generated
 */
public interface NextSection extends EObject
{
} // NextSection
