/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.question.q.SectionReference#getSection <em>Section</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.question.q.QPackage#getSectionReference()
 * @model
 * @generated
 */
public interface SectionReference extends NextSection
{
  /**
   * Returns the value of the '<em><b>Section</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Section</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Section</em>' reference.
   * @see #setSection(Section)
   * @see ox.xtext.peweb.question.q.QPackage#getSectionReference_Section()
   * @model
   * @generated
   */
  Section getSection();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.question.q.SectionReference#getSection <em>Section</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Section</em>' reference.
   * @see #getSection()
   * @generated
   */
  void setSection(Section value);

} // SectionReference
