/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.question.q.Section#getName <em>Name</em>}</li>
 *   <li>{@link ox.xtext.peweb.question.q.Section#getSectionContents <em>Section Contents</em>}</li>
 *   <li>{@link ox.xtext.peweb.question.q.Section#getNextSection <em>Next Section</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.question.q.QPackage#getSection()
 * @model
 * @generated
 */
public interface Section extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ox.xtext.peweb.question.q.QPackage#getSection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.question.q.Section#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Section Contents</b></em>' containment reference list.
   * The list contents are of type {@link ox.xtext.peweb.question.q.SectionContents}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Section Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Section Contents</em>' containment reference list.
   * @see ox.xtext.peweb.question.q.QPackage#getSection_SectionContents()
   * @model containment="true"
   * @generated
   */
  EList<SectionContents> getSectionContents();

  /**
   * Returns the value of the '<em><b>Next Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next Section</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next Section</em>' containment reference.
   * @see #setNextSection(NextSection)
   * @see ox.xtext.peweb.question.q.QPackage#getSection_NextSection()
   * @model containment="true"
   * @generated
   */
  NextSection getNextSection();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.question.q.Section#getNextSection <em>Next Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next Section</em>' containment reference.
   * @see #getNextSection()
   * @generated
   */
  void setNextSection(NextSection value);

} // Section
