/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.ui.contentassist;

import ox.xtext.peweb.arithmetic.ui.contentassist.AbstractArithmeticProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ArithmeticProposalProvider extends AbstractArithmeticProposalProvider {
}
