/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.arithmetic.arithmetic.FunctionCall#getFunc <em>Func</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' reference.
   * @see #setFunc(AbstractDefinition)
   * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getFunctionCall_Func()
   * @model
   * @generated
   */
  AbstractDefinition getFunc();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.arithmetic.arithmetic.FunctionCall#getFunc <em>Func</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(AbstractDefinition value);

} // FunctionCall
