/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.arithmetic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
