/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getIndexVariable <em>Index Variable</em>}</li>
 *   <li>{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getLower <em>Lower</em>}</li>
 *   <li>{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getUpper <em>Upper</em>}</li>
 *   <li>{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getSumExpression()
 * @model
 * @generated
 */
public interface SumExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Index Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index Variable</em>' containment reference.
   * @see #setIndexVariable(DeclaredParameter)
   * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getSumExpression_IndexVariable()
   * @model containment="true"
   * @generated
   */
  DeclaredParameter getIndexVariable();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getIndexVariable <em>Index Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index Variable</em>' containment reference.
   * @see #getIndexVariable()
   * @generated
   */
  void setIndexVariable(DeclaredParameter value);

  /**
   * Returns the value of the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lower</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' attribute.
   * @see #setLower(int)
   * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getSumExpression_Lower()
   * @model
   * @generated
   */
  int getLower();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getLower <em>Lower</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' attribute.
   * @see #getLower()
   * @generated
   */
  void setLower(int value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Upper</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' attribute.
   * @see #setUpper(int)
   * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getSumExpression_Upper()
   * @model
   * @generated
   */
  int getUpper();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getUpper <em>Upper</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' attribute.
   * @see #getUpper()
   * @generated
   */
  void setUpper(int value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage#getSumExpression_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.arithmetic.arithmetic.SumExpression#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // SumExpression
