/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ox.xtext.peweb.question.ui.AbstractQUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QUiModule extends AbstractQUiModule {
  public QUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
