/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ox.xtext.peweb.question.q.NextSection;
import ox.xtext.peweb.question.q.QPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Next Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NextSectionImpl extends MinimalEObjectImpl.Container implements NextSection
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NextSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QPackage.Literals.NEXT_SECTION;
  }

} //NextSectionImpl
