/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ox.xtext.peweb.question.q.QPackage;
import ox.xtext.peweb.question.q.SectionContents;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Section Contents</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SectionContentsImpl extends MinimalEObjectImpl.Container implements SectionContents
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SectionContentsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QPackage.Literals.SECTION_CONTENTS;
  }

} //SectionContentsImpl
