/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.q.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import ox.xtext.peweb.question.q.QPackage;
import ox.xtext.peweb.question.q.Section;
import ox.xtext.peweb.question.q.SectionReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Section Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.question.q.impl.SectionReferenceImpl#getSection <em>Section</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SectionReferenceImpl extends NextSectionImpl implements SectionReference
{
  /**
   * The cached value of the '{@link #getSection() <em>Section</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSection()
   * @generated
   * @ordered
   */
  protected Section section;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SectionReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QPackage.Literals.SECTION_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Section getSection()
  {
    if (section != null && section.eIsProxy())
    {
      InternalEObject oldSection = (InternalEObject)section;
      section = (Section)eResolveProxy(oldSection);
      if (section != oldSection)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, QPackage.SECTION_REFERENCE__SECTION, oldSection, section));
      }
    }
    return section;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Section basicGetSection()
  {
    return section;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSection(Section newSection)
  {
    Section oldSection = section;
    section = newSection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QPackage.SECTION_REFERENCE__SECTION, oldSection, section));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QPackage.SECTION_REFERENCE__SECTION:
        if (resolve) return getSection();
        return basicGetSection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QPackage.SECTION_REFERENCE__SECTION:
        setSection((Section)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QPackage.SECTION_REFERENCE__SECTION:
        setSection((Section)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QPackage.SECTION_REFERENCE__SECTION:
        return section != null;
    }
    return super.eIsSet(featureID);
  }

} //SectionReferenceImpl
