/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.peweb;

import com.google.inject.Injector;
import javax.servlet.annotation.WebServlet;
import org.eclipse.xtext.peweb.customview.ViewRetriever;
import org.eclipse.xtext.peweb.editorgen.ViewSpecification;
import org.eclipse.xtext.peweb.servlet.PeServlet;
import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.xbase.lib.Exceptions;
import ox.xtext.peweb.graph.peweb.GraphPeWebSetup;
import ox.xtext.peweb.graph.peweb.GraphViewRetriever;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "PeServices", urlPatterns = "/pe-service/*")
@SuppressWarnings("all")
public class GraphPeServlet extends PeServlet {
  private DisposableRegistry disposableRegistry;
  
  private Injector injector;
  
  private ViewRetriever viewRetriever;
  
  @Override
  public Injector getInjector() {
    Injector _xifexpression = null;
    if ((this.injector == null)) {
      _xifexpression = this.injector = new GraphPeWebSetup().createInjectorAndDoEMFRegistration();
    } else {
      return this.injector;
    }
    return _xifexpression;
  }
  
  @Override
  public ViewRetriever getViewRetriever() {
    if ((this.viewRetriever == null)) {
      GraphViewRetriever _graphViewRetriever = new GraphViewRetriever();
      this.viewRetriever = _graphViewRetriever;
      this.viewRetriever.nodeMap = ViewSpecification.getNodeMap();
      this.viewRetriever.componentMap = ViewSpecification.getComponentMap();
    }
    return this.viewRetriever;
  }
  
  @Override
  public void init() {
    try {
      super.init();
      this.disposableRegistry = this.getInjector().<DisposableRegistry>getInstance(DisposableRegistry.class);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Override
  public void destroy() {
    if ((this.disposableRegistry != null)) {
      this.disposableRegistry.dispose();
      this.disposableRegistry = null;
    }
    super.destroy();
  }
}
