/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.peweb;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ox.xtext.peweb.graph.GraphRuntimeModule;
import ox.xtext.peweb.graph.GraphStandaloneSetup;
import ox.xtext.peweb.graph.ide.GraphIdeModule;
import ox.xtext.peweb.graph.peweb.GraphPeWebModule;

/**
 * Initialization support for running Xtext languages in pe web applications.
 */
@SuppressWarnings("all")
public class GraphPeWebSetup extends GraphStandaloneSetup {
  @Override
  public Injector createInjector() {
    GraphRuntimeModule _graphRuntimeModule = new GraphRuntimeModule();
    GraphIdeModule _graphIdeModule = new GraphIdeModule();
    GraphPeWebModule _graphPeWebModule = new GraphPeWebModule();
    return Guice.createInjector(Modules2.mixin(_graphRuntimeModule, _graphIdeModule, _graphPeWebModule));
  }
}
