/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.peweb

import java.io.File
import org.eclipse.emf.common.util.URI
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider

class QPeResourceBaseProvider implements IResourceBaseProvider{ 
  
  public override URI getFileURI(String resourceId) { 
    return URI.createFileURI((("user-files" + File.separator) + resourceId)); 
  } 
}
