/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.graph;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.graph.graph.MoveStmt#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.graph.graph.GraphPackage#getMoveStmt()
 * @model
 * @generated
 */
public interface MoveStmt extends Statement
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(Declaration)
   * @see ox.xtext.peweb.graph.graph.GraphPackage#getMoveStmt_Var()
   * @model
   * @generated
   */
  Declaration getVar();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.graph.graph.MoveStmt#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Declaration value);

} // MoveStmt
