/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.graph;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.peweb.graph.graph.WhileStmt#getExpr <em>Expr</em>}</li>
 *   <li>{@link ox.xtext.peweb.graph.graph.WhileStmt#getStmts <em>Stmts</em>}</li>
 * </ul>
 *
 * @see ox.xtext.peweb.graph.graph.GraphPackage#getWhileStmt()
 * @model
 * @generated
 */
public interface WhileStmt extends Statement
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see ox.xtext.peweb.graph.graph.GraphPackage#getWhileStmt_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link ox.xtext.peweb.graph.graph.WhileStmt#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

  /**
   * Returns the value of the '<em><b>Stmts</b></em>' containment reference list.
   * The list contents are of type {@link ox.xtext.peweb.graph.graph.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stmts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmts</em>' containment reference list.
   * @see ox.xtext.peweb.graph.graph.GraphPackage#getWhileStmt_Stmts()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStmts();

} // WhileStmt
