/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.peweb;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link GraphPeWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractGraphPeWebModule extends DefaultWebModule {

}
