/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.ide;

import ox.xtext.peweb.graph.ide.AbstractGraphIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GraphIdeModule extends AbstractGraphIdeModule {
}
