/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.ui.contentassist;

import ox.xtext.peweb.question.ui.contentassist.AbstractQProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QProposalProvider extends AbstractQProposalProvider {
}
