/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ox.xtext.peweb.graph.ui.AbstractGraphUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GraphUiModule extends AbstractGraphUiModule {
  public GraphUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
