/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ox.xtext.peweb.question.QRuntimeModule;
import ox.xtext.peweb.question.QStandaloneSetup;
import ox.xtext.peweb.question.ide.QIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class QIdeSetup extends QStandaloneSetup {
  @Override
  public Injector createInjector() {
    QRuntimeModule _qRuntimeModule = new QRuntimeModule();
    QIdeModule _qIdeModule = new QIdeModule();
    return Guice.createInjector(Modules2.mixin(_qRuntimeModule, _qIdeModule));
  }
}
