/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question.ide;

import ox.xtext.peweb.question.ide.AbstractQIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QIdeModule extends AbstractQIdeModule {
}
