/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.arithmetic.arithmetic.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import ox.xtext.peweb.arithmetic.arithmetic.AbstractDefinition;
import ox.xtext.peweb.arithmetic.arithmetic.ArithmeticFactory;
import ox.xtext.peweb.arithmetic.arithmetic.ArithmeticPackage;
import ox.xtext.peweb.arithmetic.arithmetic.DeclaredParameter;
import ox.xtext.peweb.arithmetic.arithmetic.Definition;
import ox.xtext.peweb.arithmetic.arithmetic.Div;
import ox.xtext.peweb.arithmetic.arithmetic.Evaluation;
import ox.xtext.peweb.arithmetic.arithmetic.Expression;
import ox.xtext.peweb.arithmetic.arithmetic.FunctionCall;
import ox.xtext.peweb.arithmetic.arithmetic.Import;
import ox.xtext.peweb.arithmetic.arithmetic.Minus;
import ox.xtext.peweb.arithmetic.arithmetic.Multi;
import ox.xtext.peweb.arithmetic.arithmetic.NumberLiteral;
import ox.xtext.peweb.arithmetic.arithmetic.Plus;
import ox.xtext.peweb.arithmetic.arithmetic.Statement;
import ox.xtext.peweb.arithmetic.arithmetic.SumExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ArithmeticFactoryImpl extends EFactoryImpl implements ArithmeticFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ArithmeticFactory init()
  {
    try
    {
      ArithmeticFactory theArithmeticFactory = (ArithmeticFactory)EPackage.Registry.INSTANCE.getEFactory(ArithmeticPackage.eNS_URI);
      if (theArithmeticFactory != null)
      {
        return theArithmeticFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ArithmeticFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArithmeticFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ArithmeticPackage.MODULE: return createModule();
      case ArithmeticPackage.IMPORT: return createImport();
      case ArithmeticPackage.STATEMENT: return createStatement();
      case ArithmeticPackage.DEFINITION: return createDefinition();
      case ArithmeticPackage.DECLARED_PARAMETER: return createDeclaredParameter();
      case ArithmeticPackage.ABSTRACT_DEFINITION: return createAbstractDefinition();
      case ArithmeticPackage.EVALUATION: return createEvaluation();
      case ArithmeticPackage.EXPRESSION: return createExpression();
      case ArithmeticPackage.SUM_EXPRESSION: return createSumExpression();
      case ArithmeticPackage.PLUS: return createPlus();
      case ArithmeticPackage.MINUS: return createMinus();
      case ArithmeticPackage.MULTI: return createMulti();
      case ArithmeticPackage.DIV: return createDiv();
      case ArithmeticPackage.NUMBER_LITERAL: return createNumberLiteral();
      case ArithmeticPackage.FUNCTION_CALL: return createFunctionCall();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ox.xtext.peweb.arithmetic.arithmetic.Module createModule()
  {
    ModuleImpl module = new ModuleImpl();
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Definition createDefinition()
  {
    DefinitionImpl definition = new DefinitionImpl();
    return definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeclaredParameter createDeclaredParameter()
  {
    DeclaredParameterImpl declaredParameter = new DeclaredParameterImpl();
    return declaredParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractDefinition createAbstractDefinition()
  {
    AbstractDefinitionImpl abstractDefinition = new AbstractDefinitionImpl();
    return abstractDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Evaluation createEvaluation()
  {
    EvaluationImpl evaluation = new EvaluationImpl();
    return evaluation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SumExpression createSumExpression()
  {
    SumExpressionImpl sumExpression = new SumExpressionImpl();
    return sumExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Plus createPlus()
  {
    PlusImpl plus = new PlusImpl();
    return plus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Minus createMinus()
  {
    MinusImpl minus = new MinusImpl();
    return minus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Multi createMulti()
  {
    MultiImpl multi = new MultiImpl();
    return multi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Div createDiv()
  {
    DivImpl div = new DivImpl();
    return div;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NumberLiteral createNumberLiteral()
  {
    NumberLiteralImpl numberLiteral = new NumberLiteralImpl();
    return numberLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionCall createFunctionCall()
  {
    FunctionCallImpl functionCall = new FunctionCallImpl();
    return functionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArithmeticPackage getArithmeticPackage()
  {
    return (ArithmeticPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ArithmeticPackage getPackage()
  {
    return ArithmeticPackage.eINSTANCE;
  }

} //ArithmeticFactoryImpl
