/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.question


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QStandaloneSetup extends QStandaloneSetupGenerated {

	def static void doSetup() {
		new QStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
