/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.peweb.graph.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ox.xtext.peweb.graph.ui.internal.GraphActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GraphActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GraphActivator activator = GraphActivator.getInstance();
		return activator != null ? activator.getInjector(GraphActivator.OX_XTEXT_PEWEB_GRAPH_GRAPH) : null;
	}

}
